### ISSUE TITLE
Cookiemonsters Issue

### ISSUE THREAD

**Issue by Berabjesus** [tadeuasarro/ror-social-scaffold#1]
## Great Job @tadeuasarro 
- Suggestions
- Only the posts of the user's friend are displayed.
## optional
- Number of friend requests are seen
![image](https://user-images.githubusercontent.com/64360974/96004126-acd26780-0e43-11eb-8461-565fa4ef23b1.png)

**Comment by tadeuasarro** [comment]
### Closed
- Only friends and self-posts are displayed
